spring.application.name=techw-ecommerce
spring.datasource.url=jdbc:postgresql://db:5432/TechW
spring.datasource.username=jaku
spring.datasource.password=jaku03895!
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Seed Database
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# JWT Configuration
jwt.secret=9a4f434243414242424141414242424141414242424141414242424141414242
jwt.expiration=86400000
