spring.application.name=techw-ecommerce
spring.datasource.url=jdbc:sqlserver://db:1433;databaseName=TechW;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=Passw0rd123!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# JWT Configuration
jwt.secret=9a4f434243414242424141414242424141414242424141414242424141414242
jwt.expiration=86400000
